name:  Solicitud de Nuevo Repositorio
description: Solicita la creaci贸n de un nuevo repositorio en GitHub
title: 'Nuevo Repositorio - [NOMBRE_DEL_REPOSITORIO]'

body:
  - type: markdown
    attributes:
      value: |
        Gracias por solicitar la creaci贸n de un nuevo repositorio. Por favor, completa la siguiente informaci贸n de la manera m谩s detallada posible.

  - type: input
    id: name
    attributes:
      label: ' Nombre del Repositorio:'
      description: 'Nombre exacto que tendr谩 el repositorio en GitHub (ej. `bancadigital-ms-<name>`, `bancadigital-lib-<name>`, `bancadigital-infra-name`). Utiliza min煤sculas y guiones para separar palabras.'
      placeholder: 'ej. mi-proyecto-nuevo'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: ' Descripci贸n del Repositorio:'
      description: 'Una breve descripci贸n del prop贸sito y funcionalidad del repositorio.'
      placeholder: 'ej. Servicio REST para la gesti贸n de usuarios.'
    validations:
      required: true

  - type: dropdown
    id: template
    attributes:
      label: ' Tipo de Template a Utilizar:'
      description: 'Selecciona el tipo de template base para este repositorio.'
      options:
        - 'spring-boot-ms'
        - 'terraform-aws-module'
    validations:
      required: true
