name: Automated Repository Creation

on:
  issues:
    types: [opened]

jobs:
  create-repository:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Issue
        id: parser
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: create-repo.yml
          workspace: ${{ github.workspace }}
    
      - name: Output Issue JSON
        id: output-issue
        run: echo ${{ steps.parser.outputs.json }}
