name: Automated Repository Creation

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.set-env.outputs.repo-name }}
      repo-description: ${{ steps.set-env.outputs.repo-description }}
      repo-template: ${{ steps.set-env.outputs.repo-template }}
    steps:
      - name: Add reaction to Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions \
            -f content='eyes'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Issue
        id: parser
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: create-repository.yml
          workspace: ${{ github.workspace }}

      - name: Set env vars from Issue JSON
        id: set-env
        run: |
          echo '${{ steps.parser.outputs.json }}' > issue.json
          echo "repo-name=$(jq -r .name issue.json)" >> $GITHUB_OUTPUT
          echo "repo-description=$(jq -r .description issue.json)" >> $GITHUB_OUTPUT
          echo "repo-template=$(jq -r '.template[0]' issue.json)" >> $GITHUB_OUTPUT

  create-repository:
    needs: parse-issue
    environment:
      name: Setup Repository
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID_SETUP_REPO }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_SETUP_REPO }}
          owner: ${{ github.repository_owner }}

      - name: Create Repository
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh repo create "${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}" --public --description "${{ needs.parse-issue.outputs.repo-description }}" --template "${{ needs.parse-issue.outputs.repo-template }}"

  setup-repository:
    needs: 
      - parse-issue
      - create-repository
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID_SETUP_REPO }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_SETUP_REPO }}
          owner: ${{ github.repository_owner }}

      - name: Add Topics
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh repo edit "${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}" --delete-branch-on-merge
          case "${{ needs.parse-issue.outputs.repo-template }}" in
              "terraform-aws-module")
                  gh repo edit "${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}" --add-topic terraform --add-topic iac
                  ;;
              "spring-boot-ms")
                  gh repo edit "${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}" --add-topic micro
                  ;;
              *)
                  echo "Selecciona un repositorio valido"
                  ;;
          esac

      - name: Add Repository to Team
        id: permission
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          TEAM: devops
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/${{ github.repository_owner }}/teams/$TEAM/repos/${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }} \
          -f "permission=push"

      - name: Set Custom Properties
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}/properties/values \
            -f "properties[][property_name]=ownership" -f "properties[][value]=Kokodoki"

  report-status:
    if: always()
    permissions:
      issues: write
    needs:
      - parse-issue
      - create-repository
      - setup-repository
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Report Status
        run: |
          MSG="### 📢 Reporte\n\n"
          MSG+="- Creación del repositorio: **${{ needs.create-repository.result }}**\n"
          MSG+="- Configuración del repositorio: **${{ needs.setup-repository.result }}**\n\n"
          if [ "${{ needs.create-repository.result }}" = "success" ] && [ "${{ needs.setup-repository.result }}" = "success" ]; then
            REPO_URL="https://github.com/${{ github.repository_owner }}/${{ needs.parse-issue.outputs.repo-name }}"
            MSG+="#### ✅ El workflow finalizó correctamente y el repositorio fue creado/configurado.\n\n"
            MSG+="#### 🔗 Repositorio: [${{ needs.parse-issue.outputs.repo-name }}]($REPO_URL)\n"
          else
            MSG+="### ❌ El workflow falló. Por favor revisa los logs para más detalles.\n"
          fi
          gh issue comment "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --body "$(echo -e $MSG)"

      - name: Close Issue
        run: |
          gh issue close "${{ github.event.issue.number }}" --repo "${{ github.repository }}" --reason completed
