name: Reusable Workflow Base

on:
  workflow_call:
env:
  EXAMPLE_ENV: ${{ vars.EXAMPLE_VAR}}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print inputs & secrets
        run: |
          echo "Input recibido: ${{ vars.EXAMPLE_VAR }}"
          echo "Secreto recibido: ${{ secrets.EXAMPLE_SECRET }}"
          echo "Variable de entorno: ${{ env.EXAMPLE_ENV }}"
