name: Reusable Workflow Base

on:
  workflow_call:
    # inputs:
    #   example-input:
    #     required: false
    #     type: string
    # secrets:
    #   EXAMPLE_SECRET:
    #     required: true
env:
  EXAMPLE_ENV: ${{ vars}}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print inputs & secrets
        run: |
          echo "Input recibido: ${{ vars.EXAMPLE_VAR }}"
          echo "Secreto recibido: ${{ secrets.EXAMPLE_SECRET }}"
          echo "Variable de entorno: ${{ env.EXAMPLE_ENV }}"
