name: Reusable Workflow Base

on:
  workflow_call:
    inputs:
      example-input:
        required: false
        type: string
    secrets:
      EXAMPLE_SECRET:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print inputs & secrets
        run: |
          echo "Input recibido: ${{ inputs.example-input }}"
          echo "Secreto recibido: ${{ secrets.EXAMPLE_SECRET }}"
